#!/usr/bin/env ruby
require_relative 'aoc'
input = AOC.read(2)

reports = []
input.each_line do |line|
  reports << line.split.map { |val| val.to_i }
end

def safe?(report)
  safe = false
  report.each_with_index do |_, i|
    if i == report.length-1
      safe = true
      break
    elsif (report[i] < report[i+1]) and ((report[i] - report[i+1]).abs <= 3)
      next
    else
      safe = false
      break
    end
  end
  if !safe
    report.each_with_index do |_, i|
      if i == report.length-1
        safe = true
        break
      elsif (report[i] > report[i+1]) and ((report[i] - report[i+1]).abs <= 3)
        next
      else
        safe = false
        break
      end
    end
  end
  return safe
end

count = 0
reports.each do |report|
  if safe? report
    count += 1
  else
    (0...report.length).each do |i|
      if safe?(report[0...i] + report[(i+1)..-1])
        count += 1
        break
      end
    end
  end
end
puts count
