#!/usr/bin/env ruby
require_relative 'aoc'
input = AOC.read(3)

instructions = input.scan /mul\(\d{1,3},\d{1,3}\)/
sum = 0
instructions.each do |instruction|
  a_trash, b_trash = instruction.split(',')
  a = a_trash.gsub(/\D/, '').to_i
  b = b_trash.gsub(/\D/, '').to_i
  sum += a * b
end
puts sum
