#!/usr/bin/env ruby
require_relative 'aoc'
input = AOC.read(3)

sanitized = ""
enabled = true
input.each_char.with_index do |c,i|
  if input[i] == 'd' && input[i+1] == 'o' && input[i+2] == '(' && input[i+3] == ')'
    enabled = true
  elsif input[i] == 'd' && input[i+1] == 'o' && input[i+2] == 'n' && input[i+3] == "'" && input[i+4] == 't' && input[i+5] == '(' && input[i+6] == ')'
    enabled = false
  end
  if enabled
    sanitized << c
  end
end

instructions = sanitized.scan /mul\(\d{1,3},\d{1,3}\)/
sum = 0
instructions.each do |instruction|
  a_trash, b_trash = instruction.split(',')
  a = a_trash.gsub(/\D/, '').to_i
  b = b_trash.gsub(/\D/, '').to_i
  sum += a * b
end
puts sum
