#!/usr/bin/env ruby
input = <<'EOF'
MMMSXXMASM
MSAMXMSMSA
AMXSXMAAMM
MSAMASMSMX
XMASAMXAMM
XXAMMXXAMA
SMSMSASXSS
SAXAMASAAA
MAMMMXMMMM
MXMXAXMASX
EOF

matrix = []

# Find row length.
row_length = nil
input.each_char.with_index do |char, i|
  if char == "\n"
    row_length = i
    break
  end
end

# Find column length and read characters into a list used as a matrix.
column_length = 0
input.each_char.with_index do |char, i|
  if char == "\n"
    column_length += 1
    next
  end
  matrix << char
end

#########################################################################################
# YOU'RE ENTERING THE MATRIX                                                            #
# YOUR LIFE IS A LIE MADE BY AN AUTONOMOUS AI USING YOU AS A DURACELL BATTERY FOR POWER #
# WAKE UP                                                                               #
# (and learn kung fu)                                                                   #
#########################################################################################

lines = []

# Read row lines.
line = ""
for j in 0...row_length
  for i in 0...column_length
    line << matrix[(i + (j * row_length))]
  end
end
lines << line
lines << line.reverse

# Read column lines.
#line = ""
#for i in 0...column_length
#  for j in 0...row_length
#    line << matrix[(i + (j * row_length))]
#  end
#end
#lines << line
#lines << line.reverse

# Read cross from left to right.
#line = ""
#for j in (row_length-1).downto(0)
#  for j_2 in j.downto(0)
#    for i_2 in 0...column_length
#      line << matrix[i_2 + (j_2 * row_length)]
#    end
#  end
#  lines << line
#  lines << line.reverse
#end

# TODO: Read cross from right to left.

# Count the number of XMAS.
count = 0
lines.each do |line|
  count += line.scan(/XMAS/).size
end
#puts count
puts "count = #{count} == 18? #{count == 18}"
