#!/usr/bin/env ruby
#require_relative 'aoc'
#input = AOC.read(5)
input = <<'EOF'
47|53
97|13
97|61
97|47
75|29
61|13
75|53
29|13
97|29
53|29
61|53
97|53
61|29
47|13
75|47
97|75
47|61
75|61
47|29
75|13
53|13

75,47,61,53,29
97,61,53,29,13
75,29,13
75,97,47,61,53
61,13,29
97,13,75,29,47
EOF

rules = input.split("\n\n")[0]
updates = input.split("\n\n")[1].split("\n").map{|update| update.split(",")}

# Get middle page index.
def middle_index(update)
  (update.length / 2).floor
end

# Get middle page number.
def middle_number(update)
  update[middle_index(update)]
end

# TODO: Check if the update is in the correct order.
def correct?(update)
end

puts "TODO"
