#!/usr/bin/env ruby
require_relative 'aoc'
input = AOC.read(9).strip

blocks = ""
j = 0
input.each_char.with_index do |n, i|
  if i.even? # n block file.
    n.to_i.times do
      blocks << j.to_s
    end
    j += 1
  else # free block space.
    n.to_i.times do
      blocks << '.'
    end
  end
end
puts blocks
