#!/usr/bin/env ruby
require_relative 'aoc'
input = AOC.read(9).strip

blocks = []
j = 0
input.each_char.with_index do |n, i|
  if i.even? # n block file.
    n.to_i.times do
      blocks << j.to_s
    end
    j += 1
  else # free block space.
    n.to_i.times do
      blocks << '.'
    end
  end
end

last_i = 0
(blocks.length-1).downto(0).each do |j|
  if blocks[j] != '.'
    ((last_i+1)...j).each do |i|
      if blocks[i] == '.'
        blocks[i], blocks[j] = blocks[j], blocks[i]
        last_i = i
        break
      end
    end
  end
end

result = 0
blocks.each_with_index do |c, i|
  next if c == '.'
  result += i * c.to_i
end
puts result
