#!/usr/bin/env ruby
Dir.entries(Dir.pwd).select do |file|
  file.match?(/^\d[ab]$/) # Regular expression for a number followed by either a or b.
end.sort.each do |solution|
  puts "#{solution}: #{`./#{solution}`}"
end
